<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search this list_Account-search-input</name>
   <tag></tag>
   <elementGuidId>19507fbe-7b26-4f88-92d1-83a6897c9670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-191</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-191']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6990c44-d731-4fdb-89fb-2af409e8cfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>4e5a61ff-2823-41f0-9198-e8baa4cfd224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>bb791f3a-fdef-4935-9d7f-d702f28f0916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-191</value>
      <webElementGuid>e1f46a51-88ed-455d-8d74-e1b4b4529aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa069b86-94f0-4cbd-ab0e-8a106c545594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Recently Viewed list view.</value>
      <webElementGuid>a2ae8db3-8511-4ac3-8598-abd6e07b4971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-191</value>
      <webElementGuid>40908cd4-97cc-44bd-8776-0e51e0c9d412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search this list...</value>
      <webElementGuid>03d57d73-2a28-4b76-8524-7f52dad690b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Account-search-input</value>
      <webElementGuid>c13849cb-5b0c-4655-aabe-49bccf8e9396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>listviewSearchTooltip-181</value>
      <webElementGuid>a1c3ebfa-449c-4a43-aeda-2e2f78191d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-191&quot;)</value>
      <webElementGuid>1b5061d7-c74b-4e99-b50d-f6cb37b83e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-191']</value>
      <webElementGuid>b1f7b9c0-aaa5-4a88-b36c-f8ec5957ca92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_1']/div/div/div/div/div/div[2]/div[2]/force-list-view-manager-search-bar/div/lightning-input/div/div/input</value>
      <webElementGuid>a291195c-5b15-4f74-a2d0-e4c5748ce046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-input/div/div/input</value>
      <webElementGuid>fedb05cc-87a8-497c-bddd-70ea382b470e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'input-191' and @placeholder = 'Search this list...' and @name = 'Account-search-input']</value>
      <webElementGuid>745e64f3-3cab-4798-af91-4e9a2ba25613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
