<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enter 2 words in rational field</name>
   <tag></tag>
   <elementGuidId>ea8a9cf3-1195-411f-b220-d995a9eef2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-856</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::textarea[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@class = 'slds-textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0b94dd81-c96a-4cd9-9536-adf1f61f3871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-textarea</value>
      <webElementGuid>3aad2548-3f65-4e1c-bdd0-3a1fba9b8f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-856</value>
      <webElementGuid>914408c2-526f-4424-88af-df0fe474a08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32768</value>
      <webElementGuid>1b2e32b7-64f4-42b3-80ae-4cd9861c2d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-856&quot;)</value>
      <webElementGuid>715772a0-3f9b-4f40-905d-d8dee6570707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-856']</value>
      <webElementGuid>b2730591-8606-417e-b898-c3d81e4d3108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-856']</value>
      <webElementGuid>6bdf30b6-377a-41ef-8cd7-b1eae4c9eaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-509']/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-text-area/lightning-textarea/div/textarea</value>
      <webElementGuid>cba7ee79-97d8-45d3-be98-c340f83ad933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::textarea[1]</value>
      <webElementGuid>df93f4e5-ad5b-4fca-a70f-e4874c07097e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-Quote Review Required (System Populated)'])[1]/preceding::textarea[1]</value>
      <webElementGuid>9ee193bc-e945-42ec-a9c8-932772d8359f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Terms On Quote'])[1]/preceding::textarea[1]</value>
      <webElementGuid>48f8fabb-229f-4254-9312-8e022f798250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-section[10]/div/div/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-text-area/lightning-textarea/div/textarea</value>
      <webElementGuid>6757fd9f-f0af-4faa-8c1a-582623a623b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
