<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>0da88745-5064-4cf1-a507-e4578271f456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lightning-button.slds-button.flow-button__NEXT > button.slds-button.slds-button_brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30df5f9d-36d0-4259-89e1-0a0a17130391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand</value>
      <webElementGuid>41e36bd8-db6b-4aa2-acd4-eb854b3ebf30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df846754-4b56-4355-8d21-1ad42b299bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9437f311-4fdf-4b3e-af96-39a9f4124169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>d764f203-1495-4e29-a488-3f351fd72dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper-body&quot;)/div[@class=&quot;quick-actions-panel&quot;]/div[@class=&quot;slds-modal__content&quot;]/article[@class=&quot;slds-is-relative&quot;]/flowruntime-flow[1]/flowruntime-navigation-bar[@class=&quot;slds-card__footer navigationBar&quot;]/footer[@class=&quot;slds-scope footerContainer slds-grid slds-grid_align-spread&quot;]/div[@class=&quot;navigation-bar__right-align&quot;]/lightning-button[@class=&quot;slds-button flow-button__NEXT&quot;]/button[@class=&quot;slds-button slds-button_brand&quot;]</value>
      <webElementGuid>7c3c50f0-338b-484a-9525-6b573ad0a9ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>9898a210-7524-4358-ab05-f1a579e0bc59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[34]</value>
      <webElementGuid>b56cc8c3-ae78-43fb-b8b1-22e91a6acb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-body']/div[2]/div/article/flowruntime-flow/flowruntime-navigation-bar/footer/div[2]/lightning-button/button</value>
      <webElementGuid>7cd5d9ff-b10e-4020-8671-fb14959c36c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pro-Ratey Tatey 🥔'])[4]/following::button[1]</value>
      <webElementGuid>fd504682-0035-4e8c-b8ad-a0e291ef1307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::button[1]</value>
      <webElementGuid>98c94839-7d7e-4a92-b8d6-e3bb84df86cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::button[1]</value>
      <webElementGuid>0e9eda03-fb66-4f95-a5e1-f30b1ce316bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>253df4ef-88c5-4ef7-8518-ea49054cd1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-button/button</value>
      <webElementGuid>55093b56-0f0c-4dc5-8680-b3307b52bc90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
