<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Leapfrog-1114882-ffe</name>
   <tag></tag>
   <elementGuidId>b457ecef-8273-4245-b786-951e3f67b975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.--desktop > #formatted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>075d32a0-67b1-4f66-b557-7e23fe91a0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formatted</value>
      <webElementGuid>67f990cf-9f53-4a69-9bff-d5ab8d30c071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>readOnly</value>
      <webElementGuid>6044afcb-16b3-4043-9a4b-7b49f2c7d09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Leapfrog
			</value>
      <webElementGuid>439a4525-e216-40aa-9cfb-e8ac72792c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/span[@class=&quot;--desktop&quot;]/div[@id=&quot;formatted&quot;]</value>
      <webElementGuid>f7b146c5-21c2-46dd-8036-c6a0175a7297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Login  Salesforce/Page_Quote  Salesforce/iframe_Skip to the top of the activity time_2b68bf</value>
      <webElementGuid>439b8baf-3b7d-4410-a56c-0b65e2240df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ed6970e5-e2d5-48fb-ab70-0b34eb941548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>83cbd52e-1c4f-4469-8590-888f4bce188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'formatted' and (text() = '
				Leapfrog
			' or . = '
				Leapfrog
			')]</value>
      <webElementGuid>63fc8acd-2f56-4132-80db-ae4ed63552c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
