<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divcheckboxContainer-1114882-645</name>
   <tag></tag>
   <elementGuidId>87a308e8-b72b-4d8f-9959-41446f72d5e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkboxContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52972c1b-ff6d-458a-aef9-a0c8ce638bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkboxContainer</value>
      <webElementGuid>676778e2-9615-4f19-992c-1da3dd969e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;checkboxContainer&quot;]</value>
      <webElementGuid>00f8b585-df21-4cf7-a9b5-a666dba839d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Login  Salesforce/Page_Quote  Salesforce/iframe_Skip to the top of the activity timeline_vfFrameId_1691371114882</value>
      <webElementGuid>7124e7ee-4c0e-42a6-99ed-67cc4d0d70e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>10cb3979-c262-46d4-be40-f37561912b4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>d105ecf6-0e92-4f1c-8e94-89a4a2dd4fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'checkboxContainer']</value>
      <webElementGuid>b9c78da8-1d94-44fc-b74a-9983574309a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
