<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paper-button_Save-1114882-05b</name>
   <tag></tag>
   <elementGuidId>a23c3912-45f9-4faa-a69c-c84eb6eef83f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sb-page-header.--desktop > #allActions > #pcSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allActions']/paper-button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>paper-button</value>
      <webElementGuid>cfd965f1-f8a0-42fd-b00c-a219df030a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>b183d230-e152-4dd4-a47e-ff130b3fe834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pcSave</value>
      <webElementGuid>7c111c29-8bbe-41ff-abf3-654c1ba952a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd374b38-38f7-400f-9e1a-e29016326743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>50f549f1-566b-4c78-a0e8-d8f6eb023c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elevation</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4e801c94-3a29-43b7-8ac2-82dacac04e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>417dc78a-77bd-41e8-9c33-7d771576f600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>50ad336f-5814-4082-a705-cba0640628ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/sb-page-header[@class=&quot;--desktop&quot;]/div[@id=&quot;allActions&quot;]/paper-button[@id=&quot;pcSave&quot;]</value>
      <webElementGuid>00e96920-5ccf-4792-8f6b-c9307023ca56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Login  Salesforce/Page_Quote  Salesforce/iframe_Skip to the top of the activity timeline_vfFrameId_1691371114882</value>
      <webElementGuid>630878e9-ed76-473d-a220-0dcf21d71b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b779da7-9f41-49f2-a70b-166798f2e0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allActions']/paper-button[2]</value>
      <webElementGuid>fe8c64f7-c550-40fb-b924-c9a233dcadd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>77d9b526-bf36-4362-b6c1-c94582be2dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//paper-button[@id = 'pcSave' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>864aaf43-d46d-4110-992d-d21fa41e7c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
