<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paper-button_Save-1114882-05b_1</name>
   <tag></tag>
   <elementGuidId>a43f6884-58f1-4e22-b19c-ea082034c386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>paper-button</value>
      <webElementGuid>56fa87f1-13bc-4cb5-9238-3a4fba6857fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainButton</value>
      <webElementGuid>cc189bb4-e04f-4056-a8ff-fa38fdb53c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notFirst primary --desktop</value>
      <webElementGuid>8517330a-35d6-482c-b325-11b86974bd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae96a505-c57c-480d-9b11-81b4abd1bc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ea3123d4-b4aa-4e57-bed4-580fb77ac007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elevation</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4d99190c-49e5-4566-a5cc-b2407fb70b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>84aeedfc-070f-4cdf-8485-c62de4b2d87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>75747cc0-b94a-4530-9735-338bd3fa64c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/paper-button[@id=&quot;mainButton&quot;]</value>
      <webElementGuid>5debcd10-f47d-4946-a760-9af1981f5bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Login  Salesforce/Page_Quote  Salesforce/iframe_Skip to the top of the activity timeline_vfFrameId_1691371114882</value>
      <webElementGuid>9a600818-c4b4-4335-837a-5486f9d3b0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34e526d7-392b-4003-8b7a-4b84e1b2cf7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>94238a0d-5fc9-4e6e-a817-4c6ee4ecfb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//paper-button[@id = 'mainButton' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>13900a07-4f53-429b-bade-bcc1fa316ba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
