<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search this list_Account-search-input</name>
   <tag></tag>
   <elementGuidId>2f4d2b57-e28e-4b5d-9ba2-613c17662523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-191</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'search' and  @placeholder = 'Search this list...' and @name = 'Account-search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05e29f8e-29ba-4376-ad94-b02c79382239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>12a5d517-778a-486e-9834-60102f84b07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>1752c29f-2997-4c4c-86c1-b2ed8883bfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-191</value>
      <webElementGuid>42063220-e19b-43ca-968a-12f3bc3dbac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1b35b4d-3c8d-4128-814c-282406b0a785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Recently Viewed list view.</value>
      <webElementGuid>c5a048d7-b8ad-4927-944a-531513db1d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-191</value>
      <webElementGuid>f63dd739-9b1c-4da0-b02c-4698ebd3aa2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search this list...</value>
      <webElementGuid>7c576de0-729e-489d-a4a0-75df55937649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Account-search-input</value>
      <webElementGuid>7c595358-bb42-443b-b1c4-46ee006d990b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>listviewSearchTooltip-181</value>
      <webElementGuid>4fe54e7b-1e8b-41ee-b381-719508921182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-191&quot;)</value>
      <webElementGuid>e8ebe41a-d6fe-4bd9-8a91-e233adb37a47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-191']</value>
      <webElementGuid>ff2b1c8a-da32-4d5b-9fdd-59ab0df76cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_1']/div/div/div/div/div/div[2]/div[2]/force-list-view-manager-search-bar/div/lightning-input/div/div/input</value>
      <webElementGuid>49635bc5-e370-4c4c-9147-a9ddd448971c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-input/div/div/input</value>
      <webElementGuid>5a309c0c-87f3-484e-91c2-b0476f03cada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'input-191' and @placeholder = 'Search this list...' and @name = 'Account-search-input']</value>
      <webElementGuid>5cf3a775-1570-4aef-848d-0b9d2c441ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
