<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>01bdfceb-c150-4321-b0b6-49fec1150e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lightning-button.slds-button.flow-button__NEXT > button.slds-button.slds-button_brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25fbc183-7e7b-47c4-bf41-8d78ae6f7ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand</value>
      <webElementGuid>0ce8efbe-c820-4143-b7e1-fbf82966c49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4056d59b-9d44-4ba6-8139-30eda5a143cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22d14a2c-34ba-490f-95d3-c42422afec79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>fd62e174-e0b4-4a42-a022-dd448b169fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper-body&quot;)/div[@class=&quot;quick-actions-panel&quot;]/div[@class=&quot;slds-modal__content&quot;]/article[@class=&quot;slds-is-relative&quot;]/flowruntime-flow[1]/flowruntime-navigation-bar[@class=&quot;slds-card__footer navigationBar&quot;]/footer[@class=&quot;slds-scope footerContainer slds-grid slds-grid_align-spread&quot;]/div[@class=&quot;navigation-bar__right-align&quot;]/lightning-button[@class=&quot;slds-button flow-button__NEXT&quot;]/button[@class=&quot;slds-button slds-button_brand&quot;]</value>
      <webElementGuid>5891fa1e-b216-4f3b-87d0-332c0bdd6db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>768f8ac8-417a-46e5-9442-b63cdb59a41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[545]</value>
      <webElementGuid>4c190871-7934-4a38-9406-9a1db26d8689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-body']/div[2]/div/article/flowruntime-flow/flowruntime-navigation-bar/footer/div[2]/lightning-button/button</value>
      <webElementGuid>9ecdc3e4-bffa-4990-bbda-1d11e65a6cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='er'])[55]/following::button[1]</value>
      <webElementGuid>326af4b8-1993-4dd7-86e6-3bf95ef377b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='er - New opportunity created by Katalon_Proration testing'])[37]/following::button[1]</value>
      <webElementGuid>1a5a1b2b-c3bc-4e19-be9e-0a07348aebe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[6]/preceding::button[1]</value>
      <webElementGuid>53641bf7-c37e-4afc-a342-93add2a1c443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close tooltip'])[1]/preceding::button[1]</value>
      <webElementGuid>50b95695-2e46-4087-b560-884ed209916f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>bdd32e94-d81c-426d-8b56-55b9ae5b643b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-button/button</value>
      <webElementGuid>bc97cb0e-f0c6-4e81-bcac-f5cc9a8045cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
