<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>038dd32f-9bc8-4bac-b115-86bc0f85b2e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lightning-button.slds-button.flow-button__NEXT > button.slds-button.slds-button_brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type = 'button' and (text() = 'Next' or . = 'Next')])</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>550d861a-37d2-45fa-834b-1c261012890f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand</value>
      <webElementGuid>639cb81a-2701-421f-b87e-c9c613be699e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>346b3a9c-c1f1-4075-b369-39882b2395bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebfc4aa2-5eed-4b86-a365-dedd5e25f7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>f2341bd0-c1ec-43f3-b835-9f38ed231dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper-body&quot;)/div[@class=&quot;quick-actions-panel&quot;]/div[@class=&quot;slds-modal__content&quot;]/article[@class=&quot;slds-is-relative&quot;]/flowruntime-flow[1]/flowruntime-navigation-bar[@class=&quot;slds-card__footer navigationBar&quot;]/footer[@class=&quot;slds-scope footerContainer slds-grid slds-grid_align-spread&quot;]/div[@class=&quot;navigation-bar__right-align&quot;]/lightning-button[@class=&quot;slds-button flow-button__NEXT&quot;]/button[@class=&quot;slds-button slds-button_brand&quot;]</value>
      <webElementGuid>8a913dbd-b483-4f28-ae42-d5f5ab1b8069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>98323121-2b11-4dbc-937f-317a5d822d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[93]</value>
      <webElementGuid>650d5abe-4822-4b40-908b-f3ac5beafe2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-body']/div[2]/div/article/flowruntime-flow/flowruntime-navigation-bar/footer/div[2]/lightning-button/button</value>
      <webElementGuid>bc12b179-9be4-448a-9a2c-09cc580e57d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='er'])[7]/following::button[1]</value>
      <webElementGuid>0227d790-f00e-4692-9495-8b429a81b6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='er - New opportunity created by Katalon_Proration testing'])[3]/following::button[1]</value>
      <webElementGuid>99cd2609-6987-4ff1-8e4e-23a54413df50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::button[1]</value>
      <webElementGuid>18ba9f93-1ce0-41f1-95a2-16cfdb505ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>d09d5dc4-b15f-49ba-bf03-3af8eb5613ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-button/button</value>
      <webElementGuid>f5aea330-19a2-449b-9b7b-72ee4f51f902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
