<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Quote Description_input-1014</name>
   <tag></tag>
   <elementGuidId>3aa7141e-b297-40d8-8b6a-d1b90268e56e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper-body']/div[2]/div/article/flowruntime-flow/flowruntime-lwc-body/div/flowruntime-list-container/div/flowruntime-base-section/div/flowruntime-screen-field/flowruntime-lwc-field/div/flowruntime-flow-screen-input/flowruntime-input-wrapper2/div/div[2]/lightning-textarea/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-1014</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4c006a21-e58f-45c6-9b68-ed705d57448f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-textarea</value>
      <webElementGuid>45c5faa8-703a-4bdf-aa4e-29053ea08639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1014</value>
      <webElementGuid>28ace81b-1d36-419f-8e10-97b78a5c5c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1014&quot;)</value>
      <webElementGuid>de49153a-02ec-4301-b487-962983cd4f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-1014']</value>
      <webElementGuid>755444dd-5e47-480f-93c8-64faa8827c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-1014']</value>
      <webElementGuid>20d81a75-baf8-44a0-9f51-0c34d0894467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-body']/div[2]/div/article/flowruntime-flow/flowruntime-lwc-body/div/flowruntime-list-container/div/flowruntime-base-section/div/flowruntime-screen-field/flowruntime-lwc-field/div/flowruntime-flow-screen-input/flowruntime-input-wrapper2/div/div[2]/lightning-textarea/div/textarea</value>
      <webElementGuid>3c7312e4-2b04-45a5-a1a4-aee87592bf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quote Description'])[1]/following::textarea[1]</value>
      <webElementGuid>60714f36-0f31-475b-aee9-1bfae045404f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Quote'])[2]/following::textarea[1]</value>
      <webElementGuid>dbbc9049-d6aa-4829-b6db-d4a9e68c6a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Quote'])[1]/preceding::textarea[1]</value>
      <webElementGuid>0e714dca-9e8e-499a-bf23-02ec5f612a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pro-Ratey Tatey � - New opportunity created by Katalon_Proration testing'])[3]/preceding::textarea[1]</value>
      <webElementGuid>e01740a4-8eef-422f-b055-119a5f7ddf68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3c6e9492-c562-4820-b85e-6d58099a2a70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
