<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Quote Description_input-1041</name>
   <tag></tag>
   <elementGuidId>12513789-845f-4bba-b239-6f68937f6538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1041</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id = 'input-1041']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c3214379-6fe1-4d84-ac9f-0249acbf5d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-textarea</value>
      <webElementGuid>afba97cf-60c2-4296-ac76-fa78269c8bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1041</value>
      <webElementGuid>fb1ecdf8-fade-450a-8cba-ccca9e7f4bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1041&quot;)</value>
      <webElementGuid>1795f37a-45be-4777-b882-fd990ff6fe01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-1041']</value>
      <webElementGuid>060f96ed-38de-4c5c-a3f0-6885c3bc5458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-1041']</value>
      <webElementGuid>bea1ba32-4b37-4d86-9134-fad80e9b3ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-body']/div[2]/div/article/flowruntime-flow/flowruntime-lwc-body/div/flowruntime-list-container/div/flowruntime-base-section/div/flowruntime-screen-field/flowruntime-lwc-field/div/flowruntime-flow-screen-input/flowruntime-input-wrapper2/div/div[2]/lightning-textarea/div/textarea</value>
      <webElementGuid>b2e74178-8156-4b88-8d53-3361a4673de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quote Description'])[1]/following::textarea[1]</value>
      <webElementGuid>9fd49b1a-f42b-4a18-a5b4-8e46251e049f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Quote'])[2]/following::textarea[1]</value>
      <webElementGuid>92ea4a14-b341-4eff-915e-3011ef1e096f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Quote'])[1]/preceding::textarea[1]</value>
      <webElementGuid>691e228f-2588-43ae-81b4-9aded1929aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pro-Ratey Tatey � - New opportunity created by Katalon_Proration testing'])[3]/preceding::textarea[1]</value>
      <webElementGuid>b580fb37-5df4-40c3-8594-de9e0fb7c78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>82e00f0e-3d4f-4373-92ed-8e645266aeb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
