<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Not an MSA</name>
   <tag></tag>
   <elementGuidId>293374ff-646d-46f7-becf-6d3d1eac140e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-1745-1-1745 > span.slds-media__body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Not an MSA' or . = 'Not an MSA')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f43f17c7-e658-49bc-a22f-464b554d030e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>2127a072-a776-464f-8ed5-41a2619bebe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not an MSA</value>
      <webElementGuid>515249e5-f809-426c-84ab-e16910d6d1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-1745-1-1745&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>fe46590b-f2b7-484c-accd-8e9194a19c40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Not an MSA' or . = 'Not an MSA')]</value>
      <webElementGuid>6e2fbea3-4ec0-48a8-8117-1d0d85e25e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-1745-1-1745']/span[2]</value>
      <webElementGuid>5222f9d6-fa22-436c-8787-82246c83e115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[2]/following::span[2]</value>
      <webElementGuid>b64cfc5f-0856-402c-8fb6-6a9d6ae138d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[1]/following::span[7]</value>
      <webElementGuid>7c7ff2dd-51de-4d90-96f5-9ca739d0bab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year 1 of a new MSA'])[1]/preceding::span[3]</value>
      <webElementGuid>7e27f4dd-4d3a-4cf3-84ac-818873073b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[2]/span[2]</value>
      <webElementGuid>0a718325-ba07-45af-a5d6-81425fc84dbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
