<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search this list_Task-search-input</name>
   <tag></tag>
   <elementGuidId>8ef8eb88-2be6-43f6-a510-111c09a90432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-94</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'search' and @id = 'input-94' and @placeholder = 'Search this list...' and @name = 'Task-search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1feefbb2-fb4a-4326-9cb3-3b0a31da2f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>9b9ba853-63a4-4cbb-869d-bdb19b445c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>48c0295c-0d83-43bc-8360-8758c5757d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-94</value>
      <webElementGuid>1840b1b3-b439-4a8d-a7b3-4c2a97c8d454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2773b12b-0023-4b83-b2c6-20cb1754e823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-94</value>
      <webElementGuid>cf84e953-b739-4f14-9fb9-33de1c721436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search this list...</value>
      <webElementGuid>70338172-41bc-4505-b3fe-e89c84be6fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Task-search-input</value>
      <webElementGuid>ec92c9b8-5f2c-4bae-a92d-7d27d35fc7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>listviewSearchTooltip-86</value>
      <webElementGuid>022f17ee-44d6-4f74-90a6-2e2268d88437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search Open Training list view.</value>
      <webElementGuid>acb7e68a-96e3-447b-ba01-d960d9581f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-94&quot;)</value>
      <webElementGuid>a927a038-e480-49b8-aee3-865334f537dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'input-94' and @placeholder = 'Search this list...' and @name = 'Task-search-input']</value>
      <webElementGuid>ddc90287-ce62-4bc9-9934-eaf41cabe1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-94']</value>
      <webElementGuid>60cbfc93-9759-42a8-9f64-e3eedac881fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/div/div[2]/div/div[2]/div[2]/div/div/div[2]/div[3]/force-list-view-manager-search-bar/div/lightning-input/div/div/input</value>
      <webElementGuid>9b13a661-8594-4623-9ba7-eda2f5edfdad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-input/div/div/input</value>
      <webElementGuid>7a402fbd-5d32-461c-8375-16fa50bc2f04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
