<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Open Training</name>
   <tag></tag>
   <elementGuidId>69162575-0fb3-4009-a4f9-93fd6233e873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.triggerLinkText.selectedListView.slds-page-header__title.slds-truncate.slds-p-right--xx-small.uiOutputText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Open Training' or . = 'Open Training')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>24230540-8ebd-416e-9be8-42bb507578b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>triggerLinkText selectedListView slds-page-header__title slds-truncate slds-p-right--xx-small uiOutputText</value>
      <webElementGuid>0cbf7f6d-89ce-403a-a2b2-e5193a791bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>59:561;a</value>
      <webElementGuid>d7d01928-8aa5-49ae-9d5a-1bc3e20a3ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>uiOutputText</value>
      <webElementGuid>78ae1703-986d-4cdc-a02b-75612816de5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Training</value>
      <webElementGuid>515d0ee6-a13f-4e20-b086-223c439f0438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;51:561;a&quot;)/div[@class=&quot;triggerLinkTextAndIconWrapper slds-page-header__name&quot;]/div[@class=&quot;slds-page-header__name-title&quot;]/h1[@class=&quot;slds-scrollable_none&quot;]/span[@class=&quot;triggerLinkText selectedListView slds-page-header__title slds-truncate slds-p-right--xx-small uiOutputText&quot;]</value>
      <webElementGuid>4e23ea1b-4f63-4789-893f-f81c4deaed6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Open Training' or . = 'Open Training')]</value>
      <webElementGuid>192a1f37-82d9-4144-91ac-ee7b5209225e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='51:561;a']/div/div/h1/span[2]</value>
      <webElementGuid>52743bba-634f-46a7-9d24-e75a30d44b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks'])[2]/following::span[1]</value>
      <webElementGuid>b0c3eccc-ce85-401d-ada4-7864e70afe7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit nav items'])[1]/following::span[10]</value>
      <webElementGuid>18e75cc6-3058-4858-b2bd-f70780ea66bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a List View: Tasks'])[1]/preceding::span[1]</value>
      <webElementGuid>0040aef9-acec-4157-a1b6-951261aae1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pin this list view.'])[1]/preceding::span[3]</value>
      <webElementGuid>17dde23d-c29b-4549-b27d-591eaaf5cd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open Training']/parent::*</value>
      <webElementGuid>9e9f5a0c-32ca-4352-944c-2e4abf3c1103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span[2]</value>
      <webElementGuid>35e656a0-48b0-406f-87a6-6134e91962b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
