<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To Address_combobox-input-679</name>
   <tag></tag>
   <elementGuidId>89dfdfc2-4908-4130-852f-60c3b163de8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-679</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'combobox-input-679' and @type = 'text' and @placeholder = 'Search Address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43995982-b360-42aa-bd28-5452a86e5a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-combobox__input slds-input slds-combobox__input-value</value>
      <webElementGuid>93520ad6-d714-4ae4-b5ca-2aa23a706c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-input-679</value>
      <webElementGuid>9017a94d-233d-40b9-9a89-b7b0a574d082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5712cbcd-e461-493d-9b12-6ff04379219a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>55d277cd-550e-4236-b77d-6eacad013a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7bde4175-1c12-462f-9de7-e639345a77ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>a06b8eff-3354-4696-85e7-985e60b18be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a1b3c4cc-d4ba-481e-9eab-2a6ace52cfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>20 moorehouse avenue christchurch</value>
      <webElementGuid>6a3d2b3c-3f5e-41c7-8b3f-978683f8d32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Address</value>
      <webElementGuid>2d53eec9-4598-4713-bf4b-ec4c36185971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>f28b96dc-7e4c-4b13-81a8-cc70769da468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>dropdown-element-679</value>
      <webElementGuid>01df622e-6765-4a94-a436-758bb11ad318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-element-679</value>
      <webElementGuid>d95bf484-6071-4fad-b6ed-634f3ad4ffd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position-id</name>
      <type>Main</type>
      <value>lgcp-1000013</value>
      <webElementGuid>45555264-fd72-4e87-a44d-fba02c0c3964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>combobox-input-679-0-679</value>
      <webElementGuid>8d2a37d6-7619-4da2-b4ad-2acf1ed90951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-input-679&quot;)</value>
      <webElementGuid>e145c4ad-77f1-484d-91d5-71e60c679d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'combobox-input-679' and @type = 'text' and @placeholder = 'Search Address']</value>
      <webElementGuid>c6d3a355-9125-476e-8c38-145ead00f7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combobox-input-679']</value>
      <webElementGuid>cf45cee1-4bd4-40d1-b362-e0b2aa9aacd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-597']/slot/flexipage-column2/div/slot/flexipage-field/slot/record_flexipage-record-field/div/span/slot/records-record-layout-input-address/lightning-input-address/fieldset/div/div/div/lightning-lookup-address/div/lightning-base-combobox/div/div/input</value>
      <webElementGuid>1d6b03c0-d8d6-4d5f-948d-549a7ea941d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-lookup-address/div/lightning-base-combobox/div/div/input</value>
      <webElementGuid>7aab0331-6aad-4835-bfa6-f70e6a75cd3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
