<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit Non-Standard Contract Documentation</name>
   <tag></tag>
   <elementGuidId>a5554d6a-12fd-42bb-bd70-9c131e35e7b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Edit Non-Standard Contract Documentation' or . = 'Edit Non-Standard Contract Documentation')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20d5bae8-30e9-480b-b297-b796ad69a5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-form-element__control</value>
      <webElementGuid>5643df35-93e1-4f65-b8be-87ac8828c328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Non-Standard Contract Documentation</value>
      <webElementGuid>f8208453-e125-419e-8e27-7b6184aa38ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionContent-1485&quot;)/div[@class=&quot;slds-form&quot;]/slot[1]/records-record-layout-row[@class=&quot;slds-form__row&quot;]/slot[@class=&quot;slds-grid slds-size_1-of-1&quot;]/records-record-layout-item[@class=&quot;slds-form__item slds-no-space&quot;]/div[@class=&quot;slds-grid slds-size_1-of-1 label-stacked&quot;]/div[@class=&quot;slds-form-element slds-hint-parent test-id__output-root slds-form-element_edit slds-form-element_readonly is-stacked is-stacked-not-editing&quot;]/div[@class=&quot;slds-form-element__control&quot;]</value>
      <webElementGuid>9451f334-5772-4de6-8dfa-49e789115b62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Edit Non-Standard Contract Documentation' or . = 'Edit Non-Standard Contract Documentation')]</value>
      <webElementGuid>02146440-4f52-4c46-9afd-14986843dde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-1485']/div/slot/records-record-layout-row/slot/records-record-layout-item[2]/div/div/div[2]</value>
      <webElementGuid>79f02f95-d934-4e1c-a1d8-b19cc2f8d4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Standard Contract Documentation'])[1]/following::div[1]</value>
      <webElementGuid>27d5c101-8057-45d4-a00f-b672676cdd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Multi-Year Master Services Agmt (MSA)'])[1]/following::div[4]</value>
      <webElementGuid>0ce0d575-0a6d-40df-b396-aca3aee5bddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New MSA With Fixed/Capped/Indexed Prices'])[1]/preceding::div[1]</value>
      <webElementGuid>b491e919-1d4c-4c8f-8c2a-65509fe4066c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//forcegenerated-detailpanel_sbqq__quote__c___012000000000000aaa___full___view___recordlayout2/records-record-layout-block/slot/records-record-layout-section[8]/div/div/div/slot/records-record-layout-row/slot/records-record-layout-item[2]/div/div/div[2]</value>
      <webElementGuid>13a010d8-2acf-48a5-bd33-a32b317086b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
