<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-icon_Selected</name>
   <tag></tag>
   <elementGuidId>badf4181-1419-49fe-a917-69cda55c3849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lightning-icon.slds-icon-utility-check.slds-icon.slds-icon--selected.slds-icon--x-small.slds-icon-text-default.slds-m-right--small.slds-button__icon.slds-icon_container.forceIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-icon[(text() = 'Selected' or . = 'Selected')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-icon</value>
      <webElementGuid>b1b44ed1-9452-4a1f-ab8d-c4bf95849cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon-name</name>
      <type>Main</type>
      <value>utility:check</value>
      <webElementGuid>e2ac1321-08e4-4897-9842-089db137d29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-icon-utility-check slds-icon slds-icon--selected slds-icon--x-small slds-icon-text-default slds-m-right--small slds-button__icon slds-icon_container forceIcon</value>
      <webElementGuid>268e1bc0-4a8a-4839-9049-f7946f643a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>2033:0</value>
      <webElementGuid>6aa54611-11c0-4759-bbc5-bf8ffa07e3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>forceIcon</value>
      <webElementGuid>496b4b66-4e20-4f71-8991-e7494977f4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selected</value>
      <webElementGuid>00295347-fad7-475e-b97e-b856fde7a4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;virtualAutocompleteListbox_46f8e85c9fb4&quot;)/li[@class=&quot;slds-dropdown__item has-icon--left   forceVirtualAutocompleteMenuOption&quot;]/a[1]/lightning-icon[@class=&quot;slds-icon-utility-check slds-icon slds-icon--selected slds-icon--x-small slds-icon-text-default slds-m-right--small slds-button__icon slds-icon_container forceIcon&quot;]</value>
      <webElementGuid>3740e83c-2735-4294-91b4-0cf3433d7fd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-icon[(text() = 'Selected' or . = 'Selected')]</value>
      <webElementGuid>c7181aba-ba3a-4692-94ce-412a1f698faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='virtualAutocompleteListbox_46f8e85c9fb4']/li/a/lightning-icon</value>
      <webElementGuid>b44bef0f-85d8-4048-a995-136bb5db9b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::lightning-icon[2]</value>
      <webElementGuid>cf586ece-1352-45af-b944-fed33004c7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dismiss'])[1]/following::lightning-icon[3]</value>
      <webElementGuid>f2a46c97-682b-45b6-a698-61b58bcbdc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Training'])[2]/preceding::lightning-icon[1]</value>
      <webElementGuid>b29ac04b-8be4-4987-af3c-a223567a0272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/lightning-icon</value>
      <webElementGuid>769824a2-4546-4a32-9705-51db9507e43c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
