<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_2023 Salesforce, Inc. All rights res_e44077</name>
   <tag></tag>
   <elementGuidId>224ed549-3e2f-4260-a45c-c9204d51c8d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#marketing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@src = 'https://c.salesforce.com/login-messages/ca/promos.html' and @id = 'marketing' and @name = 'marketing' and @title = 'Marketing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>126a6ba5-45fa-4141-8db0-3ee8288dac8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4fcfd4d9-99f1-4ccf-91e5-8b41074da6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://c.salesforce.com/login-messages/ca/promos.html</value>
      <webElementGuid>373135e4-accd-44ef-8472-1d4f8c1b5d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>marketing</value>
      <webElementGuid>eab60ab5-cf8a-4f10-9dcf-efd80aca0198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>marketing</value>
      <webElementGuid>9d82e8b0-bc3e-4709-9dc1-0a11fa705697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>471cda48-f5fa-41c7-b516-0fbc85271200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marketing</value>
      <webElementGuid>247cd659-ef22-470f-a8d1-03b4b214e228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec30889f-ab41-4fa9-9101-a9acf8a879dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts</value>
      <webElementGuid>bb1e338f-bcea-4e53-abd7-b3b8ce78be7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketing&quot;)</value>
      <webElementGuid>ecdbc8fe-09db-4cc8-8d08-6213235b790e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://c.salesforce.com/login-messages/ca/promos.html' and @id = 'marketing' and @name = 'marketing' and @title = 'Marketing']</value>
      <webElementGuid>944ab004-f1e3-48a1-9cf4-51fc2b4dc534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='marketing']</value>
      <webElementGuid>168289e0-68c8-42a6-972a-e8050fbfe474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='right']/iframe</value>
      <webElementGuid>7e5446e0-acbd-41cc-833f-83ec7224d33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>47e53ab2-db4a-4728-ad9a-b087d1597aec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
