<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search apps and items_input-363</name>
   <tag></tag>
   <elementGuidId>16031093-a7b6-4a9c-ba5f-57101a038e78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-363</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'search' and @id = 'input-363' and @placeholder = 'Search apps and items...']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4a02848-2d85-4221-9e08-d8b6486124f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>2f4b3c94-b0fe-43f3-bddb-6459a9433d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>67efc777-6c9b-4de1-b99b-47e46a7e8e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-363</value>
      <webElementGuid>01ec6d92-5d85-4a30-8b65-779695e2a1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fe85688-4069-4b4b-8449-3ee6f4ec3836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-363</value>
      <webElementGuid>d0432734-c7d7-41a7-b121-9be0d12b8045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search apps and items...</value>
      <webElementGuid>62aef4e6-dc63-47c5-9ada-69f506651325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>56ebf26f-43eb-4391-b448-caeece5cf77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3890c1a9-5323-4eb0-8646-90c4b2634a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>8e9b16d2-39e1-4e9a-af5a-dfe561e7b1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>al-menu-dropdown-apps-id-361</value>
      <webElementGuid>213ffe46-ec72-47b1-9a91-451085ce6b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34aeaac2-c747-49d4-90f2-05feb688ac05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-363&quot;)</value>
      <webElementGuid>355ac870-d840-4dff-bce0-2a87056957c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'input-363' and @placeholder = 'Search apps and items...']</value>
      <webElementGuid>db69dd4a-c865-4c2a-a611-8695c5373709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-363']</value>
      <webElementGuid>5ec500a5-b57a-4a9e-aa13-dadcb2c3f920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_5163:0']/one-app-launcher-menu/div/one-app-launcher-search-bar/lightning-input/div/div/input</value>
      <webElementGuid>733f0c27-2199-404c-a3ed-fcce59938d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//one-app-launcher-search-bar/lightning-input/div/div/input</value>
      <webElementGuid>784149a0-17c0-43bd-b78e-924b0f4943e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
