<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enter input</name>
   <tag></tag>
   <elementGuidId>006b48ef-ff01-41be-bfc1-d64f2eb70419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-2115</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::textarea[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cc45050c-f955-4d2b-80e8-c4e7e4853d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-textarea</value>
      <webElementGuid>7804802c-1f9c-4271-8a3b-e0d166b71ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-2115</value>
      <webElementGuid>ba52321a-cb2d-4b73-af02-1b05d78ee20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32768</value>
      <webElementGuid>4f6615dc-2acc-4ddc-8716-4ab497482162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-message-2115</value>
      <webElementGuid>fd37d60f-ed5c-4ac1-8a93-5920d65fce2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-2115&quot;)</value>
      <webElementGuid>de1f606a-4926-4b0b-bbf3-a890962d379c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-2115']</value>
      <webElementGuid>3d3b1aea-9651-493b-8101-75b2a0a035df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-2115']</value>
      <webElementGuid>9b1313b9-3b23-43f4-81dc-42e516da0b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-1756']/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-text-area/lightning-textarea/div/textarea</value>
      <webElementGuid>8373023b-f886-45fe-a395-0ad3b4761245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::textarea[1]</value>
      <webElementGuid>25d681d5-0426-451f-8801-fe8cb3edaf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete this field.'])[1]/preceding::textarea[1]</value>
      <webElementGuid>ce57f3e6-e86c-4edc-9d9a-1807712833e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-Quote Review Required (System Populated)'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a607257f-b272-4a25-ba1f-81f3d6f35e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-section[10]/div/div/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-text-area/lightning-textarea/div/textarea</value>
      <webElementGuid>097f24f3-3e73-4808-a3d4-90b74aec37dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
