<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Not an MSA</name>
   <tag></tag>
   <elementGuidId>6add5b13-acc8-483a-8dcb-511db8534fd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-1876-1-1876 > span.slds-media__body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Not an MSA' or . = 'Not an MSA')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a5f1ebe5-08b3-4747-9ef0-00527ce80273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>8562f3c9-0fe9-4412-a2c0-2e75dfb45125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not an MSA</value>
      <webElementGuid>ad1471e4-6c54-42ea-8b50-ac938fd1cd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-1876-1-1876&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>ff356453-0192-40a0-8abe-b676e3296e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Not an MSA' or . = 'Not an MSA')]</value>
      <webElementGuid>8d87b34c-f01d-494a-87c4-b04fa26b82fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-1876-1-1876']/span[2]</value>
      <webElementGuid>704fd79e-64f1-4b07-bdb4-47d778500de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[2]/following::span[2]</value>
      <webElementGuid>39f09246-e6bd-459b-bcfe-4db0d09f03e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[1]/following::span[7]</value>
      <webElementGuid>6ece4964-09b2-46a8-8ffc-70e08c4b01be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year 1 of a new MSA'])[1]/preceding::span[3]</value>
      <webElementGuid>4f5cb761-c79c-480f-8f85-42e3173a1850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[2]/span[2]</value>
      <webElementGuid>54aec7f7-83fd-4207-b5f4-939b9ed1f8e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
