<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close this windowNew Task General TaskT_65b539</name>
   <tag></tag>
   <elementGuidId>2aebfb77-252f-44b9-89e7-a1633e0ac42f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.panel.slds-modal.slds-fade-in-open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Close this windowNew Task: General TaskTask InformationAssigned ToPick an objectShow more »General Testing User2Press Delete to RemoveTo remove the selected record, press Backspace or Del.1 Total TaskType--None--*SubjectCallSend LetterSend QuoteOtherComplete this field.Related ToPick an objectShow more »To remove the selected record, press Backspace or Del.CommentsTip: Type Control + period to insert quick text.NameSearch and select the related contact herePick an objectShow more »To remove the selected record, press Backspace or Del.Due DateDue DateSelect a date for Due DateSet Task ReminderReminder SetReceive a reminder email at your preferred date and time by enabling a workflow. To get started, head to Setup and click Workflow.Reminder Set DateSelect a date for DateTimeAdditional InformationStatus*Not StartedPriority*NormalOther InformationCall ResultSystem InformationFormstack Submission IDErrorSave &amp; NewCancelSave' or . = 'Close this windowNew Task: General TaskTask InformationAssigned ToPick an objectShow more »General Testing User2Press Delete to RemoveTo remove the selected record, press Backspace or Del.1 Total TaskType--None--*SubjectCallSend LetterSend QuoteOtherComplete this field.Related ToPick an objectShow more »To remove the selected record, press Backspace or Del.CommentsTip: Type Control + period to insert quick text.NameSearch and select the related contact herePick an objectShow more »To remove the selected record, press Backspace or Del.Due DateDue DateSelect a date for Due DateSet Task ReminderReminder SetReceive a reminder email at your preferred date and time by enabling a workflow. To get started, head to Setup and click Workflow.Reminder Set DateSelect a date for DateTimeAdditional InformationStatus*Not StartedPriority*NormalOther InformationCall ResultSystem InformationFormstack Submission IDErrorSave &amp; NewCancelSave')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c12cede4-f393-4b19-9e89-70bb7b74644c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>1e414393-a4bb-4b01-b70f-241804b1303a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>title_1315:0</value>
      <webElementGuid>c507f2a7-8a6b-4748-9ac7-93adf32663e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>content_1315:0</value>
      <webElementGuid>cb21bbc4-471a-43c4-9e17-cc93401b10b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>00d06761-76ed-4176-91aa-f153675f6971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7483c9df-7ff0-40ad-b2e7-c723b5a70362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel slds-modal slds-fade-in-open</value>
      <webElementGuid>a50aed2b-a32a-48ea-849a-c3d171292e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1330:0</value>
      <webElementGuid>e846910a-1e39-454b-bb79-df6cee784c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close this windowNew Task: General TaskTask InformationAssigned ToPick an objectShow more »General Testing User2Press Delete to RemoveTo remove the selected record, press Backspace or Del.1 Total TaskType--None--*SubjectCallSend LetterSend QuoteOtherComplete this field.Related ToPick an objectShow more »To remove the selected record, press Backspace or Del.CommentsTip: Type Control + period to insert quick text.NameSearch and select the related contact herePick an objectShow more »To remove the selected record, press Backspace or Del.Due DateDue DateSelect a date for Due DateSet Task ReminderReminder SetReceive a reminder email at your preferred date and time by enabling a workflow. To get started, head to Setup and click Workflow.Reminder Set DateSelect a date for DateTimeAdditional InformationStatus*Not StartedPriority*NormalOther InformationCall ResultSystem InformationFormstack Submission IDErrorSave &amp; NewCancelSave</value>
      <webElementGuid>1f98f4cf-e1f5-4408-a3f1-ad3232fd29fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;desktop&quot;]/div[@class=&quot;desktop container forceStyle oneOne navexDesktopLayoutContainer lafAppLayoutHost forceAccess tablet&quot;]/div[@class=&quot;DESKTOP uiContainerManager&quot;]/div[@class=&quot;DESKTOP uiModal--medium uiModal--recordActionWrapper uiModal forceModal open active&quot;]/div[@class=&quot;panel slds-modal slds-fade-in-open&quot;]</value>
      <webElementGuid>a0888129-c5c7-4c30-bad7-4797ca624ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Close this windowNew Task: General TaskTask InformationAssigned ToPick an objectShow more »General Testing User2Press Delete to RemoveTo remove the selected record, press Backspace or Del.1 Total TaskType--None--*SubjectCallSend LetterSend QuoteOtherComplete this field.Related ToPick an objectShow more »To remove the selected record, press Backspace or Del.CommentsTip: Type Control + period to insert quick text.NameSearch and select the related contact herePick an objectShow more »To remove the selected record, press Backspace or Del.Due DateDue DateSelect a date for Due DateSet Task ReminderReminder SetReceive a reminder email at your preferred date and time by enabling a workflow. To get started, head to Setup and click Workflow.Reminder Set DateSelect a date for DateTimeAdditional InformationStatus*Not StartedPriority*NormalOther InformationCall ResultSystem InformationFormstack Submission IDErrorSave &amp; NewCancelSave' or . = 'Close this windowNew Task: General TaskTask InformationAssigned ToPick an objectShow more »General Testing User2Press Delete to RemoveTo remove the selected record, press Backspace or Del.1 Total TaskType--None--*SubjectCallSend LetterSend QuoteOtherComplete this field.Related ToPick an objectShow more »To remove the selected record, press Backspace or Del.CommentsTip: Type Control + period to insert quick text.NameSearch and select the related contact herePick an objectShow more »To remove the selected record, press Backspace or Del.Due DateDue DateSelect a date for Due DateSet Task ReminderReminder SetReceive a reminder email at your preferred date and time by enabling a workflow. To get started, head to Setup and click Workflow.Reminder Set DateSelect a date for DateTimeAdditional InformationStatus*Not StartedPriority*NormalOther InformationCall ResultSystem InformationFormstack Submission IDErrorSave &amp; NewCancelSave')]</value>
      <webElementGuid>6f1e16e1-c8c3-41d5-b30d-4a979a6b84b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::div[7]</value>
      <webElementGuid>dd228e01-4598-45fc-8285-85935f2363f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dismiss'])[1]/following::div[15]</value>
      <webElementGuid>573dd3db-05ec-4998-991b-a7e353a9c4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]</value>
      <webElementGuid>61a83bfc-86e9-40e7-a562-b4568f252163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
