<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Skip to the top of the activity time_29c1fc</name>
   <tag></tag>
   <elementGuidId>e4912450-64f0-4da1-8123-08d6d7862ee5</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;vfFrameId_1691916971643&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@title = 'accessibility title']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;oneAlohaPage&quot;]/force-aloha-page[1]/div[@class=&quot;iframe-parent slds-template_iframe slds-card&quot;]/iframe[1][count(. | //iframe[@title = 'accessibility title']) = count(//iframe[@title = 'accessibility title'])]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9b9d9154-cff7-4862-b658-9c04e3d77f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>4303fc0f-9be9-496f-8f79-2089660f560e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>fb06717f-b31d-44ab-a488-60fc487d33ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>4794fd3e-9eb4-41f3-8698-c391ccef1059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f36be41e-f5ca-4ee2-a844-98505dbcb460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfFrameId_1691916971643</value>
      <webElementGuid>444bd677-bc6e-4f4f-91d4-b19711f3a6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>accessibility title</value>
      <webElementGuid>c93d79e7-94c8-4b59-922b-51b27945de95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c802c33c-e700-458d-a96f-28eede9eef15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en-US</value>
      <webElementGuid>c0537b9c-d559-4ed1-acfb-61db6e66a39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *; microphone *; camera *; display-capture *</value>
      <webElementGuid>4263c4a2-5c77-49d0-820f-6457df459b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ef13e3e8-d2cb-438e-aa80-1138499a5edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;oneAlohaPage&quot;]/force-aloha-page[1]/div[@class=&quot;iframe-parent slds-template_iframe slds-card&quot;]/iframe[1]</value>
      <webElementGuid>a432e12b-b4fc-4773-a9d8-ade81fd0a3ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'vfFrameId_1691916971643' and @title = 'accessibility title']</value>
      <webElementGuid>b64e817d-45d3-43d6-a765-2752594ce0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='vfFrameId_1691916971643']</value>
      <webElementGuid>030149d9-9136-4e94-ba01-6bdd5559f07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[4]/div/force-aloha-page/div/iframe</value>
      <webElementGuid>0873a0bf-aa47-4300-afe3-0f1593ecb82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/force-aloha-page/div/iframe</value>
      <webElementGuid>8493ff72-7ef0-45aa-9e0c-5807d0610838</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
