<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Skip to the top of the activity time_29c1fc</name>
   <tag></tag>
   <elementGuidId>e4912450-64f0-4da1-8123-08d6d7862ee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/force-aloha-page/div/iframe</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;oneAlohaPage&quot;]/force-aloha-page[1]/div[@class=&quot;iframe-parent slds-template_iframe slds-card&quot;]/iframe[1][count(. | //iframe[@title = 'accessibility title']) = count(//iframe[@title = 'accessibility title'])]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;vfFrameId_1691916971643&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b29e7e23-bfbb-4aa1-bc04-8c053d5a025c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e554ba49-4015-4ad8-bb8b-9f3b62367617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>283fb22f-423b-47f7-9ee9-104868458836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>73b81f38-67c5-4783-acd3-74d1ccd3164a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>813ec96b-3d28-4b2b-abdd-9714098a9dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfFrameId_1691916971643</value>
      <webElementGuid>3f01e21f-d618-4cc3-9f58-4484eeaa8b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>accessibility title</value>
      <webElementGuid>e6da4102-7bf1-4361-95c7-c432e6d59f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f828ef6-b5be-49a3-8f7a-55a62c896622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en-US</value>
      <webElementGuid>f41e5986-e61f-4da4-9cfe-fdd7ab2bcbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation *; microphone *; camera *; display-capture *</value>
      <webElementGuid>2bebb639-63f2-4755-9ec9-29c7201175a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>069f98a7-47d3-4f8d-9f44-5b3a3bef88de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;oneAlohaPage&quot;]/force-aloha-page[1]/div[@class=&quot;iframe-parent slds-template_iframe slds-card&quot;]/iframe[1]</value>
      <webElementGuid>b6aea62e-6d51-4978-80c0-51db164a1600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'vfFrameId_1691916971643' and @title = 'accessibility title']</value>
      <webElementGuid>658b4d28-b679-4bef-b7ad-859fd525377b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='vfFrameId_1691916971643']</value>
      <webElementGuid>93ca826b-35f7-499f-b294-cdbb83381dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[4]/div/force-aloha-page/div/iframe</value>
      <webElementGuid>338e4764-1d8d-4a3a-9563-cb97871d34c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/force-aloha-page/div/iframe</value>
      <webElementGuid>f02cf5b1-cfb8-4362-af1e-03c1350021c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
