<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Review the errors on this page</name>
   <tag></tag>
   <elementGuidId>e66017c1-960c-4be8-9bdd-acf6e6766440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.genericNotification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Review the errors on this page.' or . = 'Review the errors on this page.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0a9cf43-55d2-42de-83cf-8f30be79e6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>genericNotification</value>
      <webElementGuid>84c63bb8-a3a7-4240-b1db-48a6349b2bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>7865:0</value>
      <webElementGuid>b7c78a68-0b46-4d71-b47c-3e88a5014d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Review the errors on this page.</value>
      <webElementGuid>da21f0b6-ef4f-403c-b625-5fe3420c8062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_4100:0&quot;)/div[@class=&quot;windowViewMode-normal oneRecordActionWrapper isModal active lafPageHost&quot;]/div[@class=&quot;isModal inlinePanel oneRecordActionWrapper&quot;]/div[@class=&quot;actionBody&quot;]/div[@class=&quot;slds-clearfix slds-card groupDependentFieldEnabled  allow-horizontal-form wide-input-break full-width forceDetailPanelDesktop&quot;]/article[1]/div[@class=&quot;pageLevelErrors&quot;]/div[@class=&quot;desktop forcePageError&quot;]/div[@class=&quot;genericNotification&quot;]</value>
      <webElementGuid>eac5db1a-9f8c-46b9-b808-33bc7b540f50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Review the errors on this page.' or . = 'Review the errors on this page.')]</value>
      <webElementGuid>7ced1d18-38d7-4ddc-b2b6-805eaecda020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_4100:0']/div/div/div/div/article/div[2]/div/div</value>
      <webElementGuid>b1796502-7d35-416d-a976-12eb908c0b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Account: Organisation'])[1]/following::div[4]</value>
      <webElementGuid>aecefb52-8853-4aa0-869c-65a756d7cbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close this window'])[1]/following::div[10]</value>
      <webElementGuid>cd7242ed-1036-4ba1-a7ce-6ccbbfeecfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='These required fields must be completed: Account Name, Organization Type, Phone, Segment'])[1]/preceding::div[1]</value>
      <webElementGuid>c2b4a0ab-74aa-459b-8b7b-d250430ea382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/article/div[2]/div/div</value>
      <webElementGuid>7f6c3584-7b4f-4455-a5a2-a929313c9383</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
